name: "build"

on:
  push:
    branches: "**"
    tags-ignore: ["**"]

env:
  RUNTIME_VERSION: 11

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"
    runs-on: "ubuntu-latest"
    steps:
      - name: "hazan"
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # tag=v2.5.1 
      - name: "checkout repository"
        uses: "actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e" # tag=v1 # comment after
      - name: "quoted, no comment, outdated"
        uses: "actions/setup-java@f0bb91606209742fe3ea40199be2f3ef195ecabf" # tag=v2
        with:
          distribution: "temurin"
          java-version: "11"
      - name: "quoted, no comment, up to date"
        uses: "actions/setup-java@860f60056505705214d223b91ed7a30f173f6142" # tag=v3
        with:
          distribution: "temurin"
          java-version: "11"
      - name: "comment, no quotes"
        uses: actions/github-script@44b873bc975058192f5279ebe7579496381f575d # tag=v2 # comment after
        with:
          script: |
            return {}
