name: "build"

on:
  push:
    branches: "**"
    tags-ignore: ["**"]

env:
  RUNTIME_VERSION: 11

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"
    runs-on: "ubuntu-latest"
    steps:
      - name: "hazan"
        uses: "actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561" # tag=v2.5.1 
      - name: "checkout repository"
        uses: "actions/checkout@v2" # comment after
      - name: "quoted, no comment, outdated"
        uses: "actions/setup-java@v2"
        with:
          distribution: "temurin"
          java-version: "11"
      - name: "quoted, no comment, up to date"
        uses: "actions/setup-java@v3"
        with:
          distribution: "temurin"
          java-version: "11"
      - name: "comment, no quotes"
        uses: actions/github-script@v6 # comment after
        with:
          script: |
            return {}
